stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

test:
  image: node:18
  stage: test
  script:
    - cd bezkoder-app
    - npm ci
    - npm test

build:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_TAG" ./bezkoder-app
    - docker push "$IMAGE_TAG"
  artifacts:
    expire_in: 1 week
    reports:
      dotenv: build.env
  after_script:
    - echo "IMAGE_TAG=$IMAGE_TAG" >> build.env

deploy:
  image: alpine:3.19
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p "${SSH_PORT:-22}" "$SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" "
        cd '$DEPLOY_PATH' &&
        export IMAGE_TAG='$IMAGE_TAG' &&
        docker compose pull &&
        docker compose up -d
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
